apiVersion: v1
kind: Service
metadata:
  name: asta-service
spec:
  selector:
    app: asta-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110